"""Documenter agent for generating incident reports."""
from .base import BaseAgent, AgentState


class DocumenterAgent(BaseAgent):
    """Generates incident reports and documentation."""

    def __init__(self):
        super().__init__(
            name="documenter",
            description="Generates incident reports and documentation"
        )

    async def process(self, state: AgentState) -> AgentState:
        """Generate comprehensive incident documentation."""
        documentation = self._generate_report(state)
        return {**state, "documentation": documentation}

    def _generate_report(self, state: AgentState) -> str:
        """Generate incident report from agent outputs."""
        incident_id = state["incident_id"]
        incident_data = state.get("incident_data", {})
        research_data = state.get("research_data", {})
        analysis = state.get("analysis", "")
        recommendation = state.get("recommendation", "")
        build_output = state.get("build_output", "")
        test_results = state.get("test_results", {})

        triage_result = {
            "incident_id": incident_id,
            "timestamp": self._timestamp(),
            "summary": self._generate_summary(incident_data, research_data),
            "severity": research_data.get("severity_indicators", {}),
            "affected_services": research_data.get("affected_services", []),
            "root_cause_analysis": analysis,
            "recommendations": recommendation,
            "remediation_script": build_output,
            "test_results": test_results,
            "status": "completed" if test_results.get("ready_for_deployment") else "needs_review"
        }

        return self._format_markdown(triage_result)

    def _generate_summary(
        self, incident_data: dict, research_data: dict
    ) -> str:
        """Generate incident summary."""
        severity = research_data.get("severity_indicators", {})
        affected = research_data.get("affected_services", [])

        return (
            f"Incident analyzed for {len(affected)} affected services. "
            f"Priority: {severity.get('priority', 'unknown')}, "
            f"Impact: {severity.get('impact_score', 'unknown')}"
        )

    def _format_markdown(self, triage_result: dict) -> str:
        """Format triage result as markdown report."""
        return f"""# Incident Triage Report

## Summary
{triage_result['summary']}

## Incident Details
- **Incident ID**: {triage_result['incident_id']}
- **Timestamp**: {triage_result['timestamp']}
- **Status**: {triage_result['status'].upper()}

## Severity Assessment
- **Priority**: {triage_result['severity'].get('priority', 'N/A')}
- **Impact Score**: {triage_result['severity'].get('impact_score', 'N/A')}
- **User Impact**: {triage_result['severity'].get('user_impact', 'N/A')}

## Affected Services
{', '.join(triage_result['affected_services']) if triage_result['affected_services'] else 'None identified'}

## Root Cause Analysis
{triage_result['root_cause_analysis']}

## Recommendations
{triage_result['recommendations']}

## Test Results
**Status**: {triage_result['test_results'].get('overall_status', 'UNKNOWN')}

{self._format_tests(triage_result['test_results'].get('tests', []))}

## Remediation Script
```bash
{triage_result['remediation_script']}
```

---
*Generated by LangGraph Incident Triage System*
"""

    def _format_tests(self, tests: list[dict]) -> str:
        """Format test results as markdown."""
        if not tests:
            return "No tests run"

        lines = []
        for test in tests:
            status = "✓" if test["passed"] else "✗"
            lines.append(f"- {status} **{test['name']}**: {test['message']}")
        return "\n".join(lines)

    def _timestamp(self) -> str:
        from datetime import datetime
        return datetime.utcnow().isoformat()
